# **Descriptive Statistics Diabetes**

## Import các thư viện cần thiết

In [1]:
import pandas as pd
import numpy as np

## Load dataset

In [5]:
names = ['preg', 'glucose', 'pres', 'skin', 'insulin', 'mass', 'pedi', 'age', 'class']
df = pd.read_csv('pima-indians-diabetes.data.csv', header=None, names=names)
df

     preg  glucose  pres  skin  insulin  mass   pedi  age  class
0       6      148    72    35        0  33.6  0.627   50      1
1       1       85    66    29        0  26.6  0.351   31      0
2       8      183    64     0        0  23.3  0.672   32      1
3       1       89    66    23       94  28.1  0.167   21      0
4       0      137    40    35      168  43.1  2.288   33      1
..    ...      ...   ...   ...      ...   ...    ...  ...    ...
763    10      101    76    48      180  32.9  0.171   63      0
764     2      122    70    27        0  36.8  0.340   27      0
765     5      121    72    23      112  26.2  0.245   30      0
766     1      126    60     0        0  30.1  0.349   47      1
767     1       93    70    31        0  30.4  0.315   23      0

[768 rows x 9 columns]

## Thông tin tổng quan về dữ liệu

- Số dòng: 768
- Số cột: 9
- Biến mục tiêu: `class` (0: không tiểu đường, 1: có tiểu đường)
- Các biến đặc trưng:
  - `Pregnancies(preg)`: Số lần mang thai
  - `Glucose`: Mức đường huyết
  - `BloodPressure (pres)`: Huyết áp
  - `SkinThickness (skin)`: Độ dày da
  - `Insulin`: Mức insulin
  - `BMI (mass)`: Chỉ số khối cơ thể
  - `DiabetesPedigreeFunction (pedi)`: Chỉ số di truyền tiểu đường
  - `Age`: Tuổi

## Kiểu dữ liệu của các thuộc tính trong DataFrame

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   preg     768 non-null    int64
 1   glucose  768 non-null    int64
 2   pres     768 non-null    int64
 3   skin     768 non-null    int64
 4   insulin  768 non-null    int64
 5   mass     768 non-null    float64
 6   pedi     768 non-null    float64
 7   age      768 non-null    int64
 8   class    768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

Kết quả cho thấy:

- Dữ liệu gồm 768 dòng và 9 cột
- Không có cột nào có giá trị NaN
- Tất cả các cột đều có kiểu dữ liệu số (`int64` hoặc `float64`)

→ Tiếp theo, chúng ta sẽ kiểm tra thống kê mô tả để hiểu phân bố dữ liệu.

## Thống kê mô tả dữ liệu

In [ ]:
df.describe()

,preg,glucose,pres,skin,insulin,mass,pedi,age,class
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

Phương thức này cho ta một cái nhìn tổng quan về dữ liệu trong dataset như:<br>
&#8226;&nbsp;&nbsp; `Count` : Đếm số lượng dòng có thông tin của 1 cột.<br>
&#8226;&nbsp;&nbsp; `mean` : Giá trị trung bình của 1 cột.<br>
&#8226;&nbsp;&nbsp; `std` : Độ lệch chuẩn của cột đó.<br>
&#8226;&nbsp;&nbsp; `min` : Giá trị nhỏ nhất của cột.<br>
&#8226;&nbsp;&nbsp; `25%, 50%, 75%` : Đây là tứ phân vị (quartiles) của cột, tìm giá trị nhỏ hơn hoặc bằng ở từng phân vị.<br>
&#8226;&nbsp;&nbsp; `max` : Giá trị lớn nhất trong cột.<br>

## Kiểm tra dữ liệu trùng lặp

In [7]:
df = df.drop_duplicates()  # Loại bỏ các dòng trùng lặp nếu có
df

     preg  glucose  pres  skin  insulin  mass   pedi  age  class
0       6      148    72    35        0  33.6  0.627   50      1
1       1       85    66    29        0  26.6  0.351   31      0
2       8      183    64     0        0  23.3  0.672   32      1
3       1       89    66    23       94  28.1  0.167   21      0
4       0      137    40    35      168  43.1  2.288   33      1
..    ...      ...   ...   ...      ...   ...    ...  ...    ...
763    10      101    76    48      180  32.9  0.171   63      0
764     2      122    70    27        0  36.8  0.340   27      0
765     5      121    72    23      112  26.2  0.245   30      0
766     1      126    60     0        0  30.1  0.349   47      1
767     1       93    70    31        0  30.4  0.315   23      0

[768 rows x 9 columns]

Có thể nhận thấy số hàng và cột không thay đổi so với dữ liệu ban đầu<br>
&rarr;&nbsp;&nbsp; Tập dữ liệu không có các hàng/ cột trùng nhau.

## Thay thế dữ liệu và thay đổi định dạng của dữ liệu

&#8226;&nbsp;&nbsp; Theo như thông tin có được ở trên thì tập dữ liệu không có giá trị thiếu (NaN) nên có thể bỏ qua phần bổ sung dữ liệu còn thiếu.<br>
&#8226;&nbsp;&nbsp; Tập dữ liệu có tất cả kiểu dữ liệu đều là dạng số, rất tiện cho máy học nên cũng không cần thiết thay đổi.<br>
&#8226;&nbsp;&nbsp; Bên cạnh đó ***target*** (`class`) có kiểu dữ `int` nên không cần thay đổi để phù hợp hơn.